# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {P:/Private/desktop/CMPEN 371/lab3/Hex2Segment_display/Hex2Segment_display.cache/wt} [current_project]
set_property parent.project_path {P:/Private/desktop/CMPEN 371/lab3/Hex2Segment_display/Hex2Segment_display.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {p:/Private/desktop/CMPEN 371/lab3/Hex2Segment_display/Hex2Segment_display.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {P:/Private/desktop/CMPEN 371/lab3/Hex2Segment_display/Hex2Segment_display.srcs/sources_1/imports/lab3/FullAdder_4Bit.vhd}
  {P:/Private/desktop/CMPEN 371/lab3/Hex2Segment_display/Hex2Segment_display.srcs/sources_1/imports/lab3/hex_display.vhd}
  {P:/Private/desktop/CMPEN 371/lab3/Hex2Segment_display/Hex2Segment_display.srcs/sources_1/new/Lab3.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{P:/Private/desktop/CMPEN 371/lab3/Hex2Segment_display/Hex2Segment_display.srcs/constrs_1/imports/lab3/Nexys4DDR_Master7.xdc}}
set_property used_in_implementation false [get_files {{P:/Private/desktop/CMPEN 371/lab3/Hex2Segment_display/Hex2Segment_display.srcs/constrs_1/imports/lab3/Nexys4DDR_Master7.xdc}}]


synth_design -top Lab3 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Lab3.dcp

catch { report_utilization -file Lab3_utilization_synth.rpt -pb Lab3_utilization_synth.pb }
